#! /bin/python

from enum import StrEnum
from typing import Type

from homeassistant.const import (
    EntityCategory,
)
from homeassistant.components.number import NumberDeviceClass, NumberMode
from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.components.binary_sensor import BinarySensorDeviceClass
from homeassistant.components.button import ButtonDeviceClass
from homeassistant.components.switch import SwitchDeviceClass
import os

enums_to_convert = [
    SwitchDeviceClass,
    ButtonDeviceClass,
    BinarySensorDeviceClass,
    SensorStateClass,
    NumberMode,
    SensorDeviceClass,
    NumberDeviceClass,
    EntityCategory,
]
enums_to_convert.sort(key=lambda x: x.__name__)


def enum_to_literal(enum_: Type[StrEnum]) -> str:
    # if not isinstance(enum_, StrEnum):
    #     raise TypeError(f"{enum_} must be a StrEnum subclass")

    values = [f"'{member}'" for member in enum_]
    return f"Literal[{', '.join(values)}]"


output = []
for enum_ in enums_to_convert:
    literal_type = enum_to_literal(enum_)
    enum_name = enum_.__name__
    output.append(f"{enum_name} = {literal_type}\n")

output = "from typing import Literal\n\n" + "\n".join(output)

# Get the directory of the current file
current_dir = os.path.dirname(os.path.abspath(__file__))
# Build the path relative to the current file's location
output_path = os.path.join(current_dir, "../servents/derived-consts.py")

with open(output_path, "w") as f:
    f.write(
        "# This file is auto-generated by utils/enum_to_literal.py from the enums in the homeassistant version in dev-dependencies\n\n"
    )
    f.write(output)
